### PR TITLE
(feat) Add custom-attributes plugin

### PR DESCRIPTION
**Pull request by zenweasel**
Resolves #N/A
Impact: **minor**  
Type: **feature**

## Issue
Extends schemas and resolvers to add a `customAttributes` plugin that allows you to add arbitrary fields to Product and Catalog w/o a code change

## Breaking changes
None

## Testing
There is currently no UI for adding custom attributes so you will need to add them to Mongo and then these attributes should be available to the GraphQL interface.

You can query these attributes like:

```graphql
{
  catalogItemProduct(slugOrId: "adidas-boys-adilette-cloudfoam-plus-slide-sandals") {
    product {
      customAttributes {
        name
        value {
          ... on CustomStringAttribute {
            stringValue: value
          }

          ... on CustomBooleanAttribute {
            boolValue: value
          }

          ... on CustomIntAttribute {
            intValue: value
          }

          ... on CustomFloatAttribute {
            floatValue: value
          }

          ... on CustomArrayAttribute {
            arrayValue: value
          }

        }
      }
    }
  }
}
```

### CODE REVIEW

**Comment by zenweasel** [comment]
@dancastellon @ajporlante Issues have been resolved. Could you please re-test?

**Comment by dancastellon** [comment]
@zenweasel Still not working for me. Am I doing this right?

1. Edited basic-reaction-product in Products collection and added:
```
"customAttributes" : [ 
        {
            "name" : "test1",
            "siteId" : "bobsstores",
            "value" : false
        }
    ]
```
2. Published product through UI. `customAttributes` was successfully copied over to `catalogProduct.product`
3. Ran this query which returned `[]` for `customAttributes`
```
{
  catalogItemProduct(slugOrId: "basic-reaction-product") {
    product {
      customAttributes {
        name
        value {
          ... on CustomBooleanAttribute {
            value
          }
        }
      }
    }
  }
}
```

**Comment by zenweasel** [comment]
@dancastellon I think I found the issue (it was specifically Boolean attributes which I wasn't testing). Please check again. This seems to be working for me (with actual imported data)

Also added a new `Array` type to accommodate some attributes which are an array of strings

**Comment by zenweasel** [comment]
@samkelleher I think this is ready for your review and merge when approved

**Pull request merged**
