### PR TITLE
feat: added Bronto email plugin as submodule

### PR DESCRIPTION
**Pull request by dancastellon**
Impact: **major**  
Type: **feature**

## Description
This PR adds the [Bronto email plugin](https://github.com/sportsdirect/reaction-plugin-email-bronto) as a Git submodule, to deliver emails via the [Bronto Email Service](https://bronto.com/). Email subject lines and content remain the same.

## Breaking changes
None

## Testing
Follow these instructions to configure and test the plugin:

_Note:_ You can skip steps 1 and 2 if you use Dan's dev account token and message:
- access token: 511D3E17-5AC7-42B6-8902-FECC585437BF
- message name: Reaction Commerce Transactional Email

#### 1) Create a message in Bronto
1. Login to Bronto
2. Messages -> All Messages -> Create New Message -> Create Email Message
3. Enter a message name. Save this for later
4. Select HTML under "Email Message Type"
5. Click Next
6. For the subject, enter `%%#subject%%`
7. For the message body, enter `%%#content%%`
8. Click Save & Close
9. Messages -> All Messages -> Click title of the new message
10. Click "Request Approval" on the left side
11. Click Submit

Note: The message will probably take 1-2 days to be approved. Once approved, proceed to the next steps.

#### 2) Create an access token in Bronto
1. Login to Bronto
2. Settings -> Platform Settings -> Data Exchange
3. Click "Add Access Token" under "SOAP API Access Tokens"
4. Enter a name for the token, select all permissions, and click "Save"
5. Copy the new token

#### 3) Plugin Installation & Configuration
1. `git submodule update --init --recursive`
1. Login as admin
1. Dashboard -> Email -> Mail Provider
1. Paste the access token
1. Enter the message name
1. Enter a from name & email - you can leave these blank to use the shop name & email defined at Dashboard -> Shop -> General

#### 4) Testing
1. Place an order and confirm you get the confirmation email
2. Confirm that entering an invalid access token or message name displays an error message at Dashboard -> Email -> Mail Provider
3. Leave the from name & email fields under the settings empty & save. View the shop name & email under Dashboard -> Shop -> General. Place an order and confirm the email you receive has the same from name & email.
4. Specify a custom from name & email under Email Provider settings. Place another email and confirm the correct from & name.
5. Change your email address under your profile and confirm you get a "Verify your new email address" email
6. Under Dashboard -> Email -> Logs confirm you can resend an email

### CODE REVIEW

**Comment by zenweasel** [comment]
@dancastellon Is there an existing Bronto email/token we can use to test rather than everybody needing to wait 1-2 days?

**Comment by dancastellon** [comment]
@zenweasel I pulled in some changes @aldeed had me make - moving the Bronto access token to an env var and changing the way `sendBrontoEmail` is registered.

**Comment by ajporlante** [comment]
In 'sendBrontoEmail.js`:
- `from` is an unused variable 
- I feel like using `!(a && b && c && d)` reads better than `!BRONTO_ACCESS_TOKEN || !fromEmail || !fromName || !messageName`
- Is authenticating needed for every email an API requirement? Isn't it already done when updating the settings?

In `getBrontoClient.js`, I think we will benefit more on having the wsdl file available locally instead of fetching it remotely for every API call.

**Comment by dancastellon** [comment]
@ajporlante Thanks - I created a PR in the Bronto repo with the changes, and updated this PR - https://github.com/sportsdirect/reaction-plugin-email-bronto/pull/3

About authenticating - while it's not required, each Bronto session only last's 20 minutes. Bronto's API docs suggest just re-authenticating each time.

**Pull request merged**
